### ISSUE TITLE
Can you help me?

### ISSUE THREAD

**Issue by fabiocostajf** [MayamaTakeshi/dtmf-detection-stream#1]
Hi,
I'm using my PC to send DTMF tones using audio output way to a debian device.
I'm using this code to send DTMF

try{
    const ToneStream = require('tone-stream')
    const Speaker = require('speaker')
   const format = {
        sampleRate: 8000, 
        bitDepth: 16,
        channels: 1
   }
  
    var ts = new ToneStream(format)
    const s = new Speaker(format)  
   function test(){
        ts = new ToneStream(format)
        console.log("alo")
        ts.add([1000, 'DTMF:1'])
        ts.add([500, 's'])
        ts.add([1000, 'DTMF:2'])
        ts.add([500, 's'])
        ts.add([1000, 'DTMF:3'])
        ts.pipe(s)

    }

    setInterval( test, 3000)
  

}catch(err){

    console.log(err)

}

and I'm using this code to receive, 
![image](https://user-images.githubusercontent.com/30118538/92027365-47a13780-ed17-11ea-8b0b-bd90d0965f1a.png)

but nothing happens, Did  you see any stuff wrong?
Thanks

**Comment by MayamaTakeshi** [comment]
Hi,
in your code, you are just sending the tones to your PC speaker.
You need to establish a communication channel between your PC and your debian device.
This can be done using UDP for example.
I have added an example on how to do it here:
  https://github.com/MayamaTakeshi/dtmf-detection-stream/tree/master/examples/over_udp

You will need to change 127.0.0.1 with the actual IP addresses of your PC and your debian device.

Obs: however, there is not much point in doing this as if you have an UDP communication channel, then you can simply send anything thought it instead of spend CPU time doing tone generation and dtmf detection.

**Comment by MayamaTakeshi** [comment]
Or maybe your debian device has a microphone and you want for it to detect DTMF traveling through air:
```
  PC Speaker --> air --> Debian Device Microphone
```
In this case, you would need to install a microphone module like this:
  https://www.npmjs.com/package/node-microphone

Then a script like this might work:
```
const DtmfDetectionStream = require('dtmf-detection-stream')
const Mic = require('node-microphone')

const format = {
	sampleRate: 8000,
	bitDepth: 16,
	channels: 1,
}

const dds = new DtmfDetectionStream(format)

dds.on('digit', digit => {
	console.log('got digit', digit)
})

const mic = new Mic({rate: 8000})

const micStream = mic.startRecording()

micStream.pipe(dds)
```
But I didn't test the above.

**Comment by fabiocostajf** [comment]
I’ll test tomorrow and I let you know...
In my case I’m using
Pc audio output (p2 cable) -> Debian device audio input (p2 cable)

**Comment by MayamaTakeshi** [comment]
Ok. I think in the Debian device, the audio input will be accessed as a microphone. So the script with node-microphone should work.

**Comment by fabiocostajf** [comment]
Unfortunately, it isn't work yet, I don't know why but I can record the DTMF tones that I send using (node-arecord) library but using mic library to get tones in real-time and process it to get the decodification of tones it's not working
[tones.zip](https://github.com/MayamaTakeshi/dtmf-detection-stream/files/5170880/tones.zip)

**Comment by MayamaTakeshi** [comment]
So nothing shows up?

I tested detecting tones from your wav file with this script:
```
$ cat detect_from_file.js 
const fs = require('fs')
const wav = require('wav')
const DtmfDetectionStream = require('dtmf-detection-stream')

if(process.argv.length !=3) {
	console.log("Please provide the wav file path")
	process.exit(1)
}

const wav_file = process.argv[2]

var file = fs.createReadStream(wav_file)
var reader = new wav.Reader()

reader.on("format", format => {
	console.log("format", format)
	var dds = new DtmfDetectionStream(format)
	dds.on('digit', digit => {
		console.log('got digit', digit)
	})
	reader.pipe(dds)
})

file.pipe(reader)

```

It was able to detect tones but incorrectly.
But at least the script was able to process the data:

```
$ node detect_from_file.js filename.wav 
format {
  audioFormat: 1,
  endianness: 'LE',
  channels: 2,
  sampleRate: 48000,
  byteRate: 192000,
  blockAlign: 4,
  bitDepth: 16,
  signed: true
}
got digit A
got digit #
got digit *
got digit 3
got digit *
got digit 1
got digit 3
... ABRIDGED...
```

So maybe there is some problem with the node-microphone library and some other mic library might work.

**Comment by fabiocostajf** [comment]
Yeah I got the same problem with node-microphone I`m keep trying here, if I have any news I'll let you know

**Comment by MayamaTakeshi** [comment]
Hi, today I had to work on related issues and performing tests with your file I realized that the original code doesn't work with sampling rates different of 8000 and 16000 (yours is 48000). So I did #3 and #4. Also, yours is a stereo file and this was also not supported. But I tested converting your file to mono (saved as https://github.com/MayamaTakeshi/dtmf-detection-stream/blob/master/examples/artifacts/digits.1111111.48000hz.1chan.wav) and it worked (you input '1' seven times):
```
takeshi@takeshi-desktop:dtmf-detection-stream$ node examples/from_wav.js examples/artifacts/digits.1111111.48000hz.1chan.wav
file_path=examples/artifacts/digits.1111111.48000hz.1chan.wav
format: {
  audioFormat: 1,
  endianness: 'LE',
  channels: 1,
  sampleRate: 48000,
  byteRate: 96000,
  blockAlign: 2,
  bitDepth: 16,
  signed: true
}
got digit 1
got digit 1
got digit 1
got digit 1
got digit 1
got digit 1
got digit 1
```
Then I did #5 and it mostly worked with your original file (saved as https://github.com/MayamaTakeshi/dtmf-detection-stream/blob/master/examples/artifacts/digits.1111111.48000hz.2chan.wav). But I am getting one extra digit '1':
```
takeshi@takeshi-desktop:dtmf-detection-stream$ node examples/from_wav.js examples/artifacts/digits.1111111.48000hz.2chan.wav
file_path=examples/artifacts/digits.1111111.48000hz.2chan.wav
format: {
  audioFormat: 1,
  endianness: 'LE',
  channels: 2,
  sampleRate: 48000,
  byteRate: 192000,
  blockAlign: 4,
  bitDepth: 16,
  signed: true
}
got digit 1
got digit 1
got digit 1
got digit 1
got digit 1
got digit 1
got digit 1
got digit 1
```
I could not solve this yet but I think if it is possible to stream the audio from the mic as mono, it should work.
Latest version 1.9.0 is available:
  https://www.npmjs.com/package/dtmf-detection-stream
Sorry to take so long to solve this but thanks for the reporting.
